# Generated by Django 4.0.4 on 2022-07-09 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', models.TextField()),
                ('eu_id', models.CharField(default='no_title', max_length=18, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('scope', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('file_type', models.CharField(choices=[('html', 'html'), ('pdf', 'pdf')], max_length=4)),
                ('publish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('date_label', models.CharField(max_length=10)),
                ('date_iso', models.CharField(max_length=10)),
                ('doc_reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.document')),
            ],
        ),
        migrations.DeleteModel(
            name='DateExtraction',
        ),
        migrations.DeleteModel(
            name='HtmlCode',
        ),
    ]
