# Generated by Django 4.0.4 on 2022-07-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_sentence_delete_dateextraction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='com_id',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='html_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
