# Generated by Django 4.0.4 on 2022-07-14 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_com_id_alter_document_html_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('header2', models.TextField()),
                ('structure', models.TextField()),
                ('cleanbody', models.TextField()),
                ('weightedsimilarities', models.TextField()),
                ('deskriptor', models.TextField()),
                ('comnumber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.document')),
            ],
        ),
    ]
