# Generated by Django 4.0.3 on 2022-04-10 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmodel',
            options={'verbose_name': 'TestModell', 'verbose_name_plural': 'TestModelle'},
        ),
    ]
