# Generated by Django 3.1.13 on 2022-04-15 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_testmodel_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
