# Generated by Django 3.1.13 on 2022-04-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateExtraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocName', models.CharField(max_length=50)),
                ('DocSentence', models.TextField()),
                ('DateLabel', models.CharField(max_length=10)),
                ('IsoDate', models.CharField(max_length=10)),
            ],
        ),
    ]
