# Generated by Django 3.1.13 on 2022-06-08 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('date_extraction', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimelineDB',
            new_name='DateExtraction',
        ),
    ]
