# Generated by Django 4.0.4 on 2022-06-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('header2', models.TextField()),
                ('body', models.TextField()),
                ('doctype', models.CharField(max_length=255)),
                ('titreobjet', models.CharField(max_length=255)),
                ('comnumber', models.CharField(max_length=255)),
                ('structure', models.CharField(max_length=255)),
                ('deskriptor', models.TextField()),
            ],
        ),
    ]
