# Generated by Django 4.0.4 on 2022-07-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_classification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentclassification',
            name='cleanbody',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentclassification',
            name='weightedsimilarities',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentclassification',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
